name: Trigger build & release fireworld
on:
  workflow_dispatch:
  #schedule:
    # Run nightly build at 01:00 UTC
  #  - cron: '00 01 * * *'

jobs:

  trigger-nightly:
    uses: ./.github/workflows/build-syncthing-fireworld.yaml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "nightly"
